<a href="https://colab.research.google.com/github/Koushik2612/fds-lab/blob/main/fds_clss_fn_30_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


student_data = {
    'student_id': range(1, 16),
    'student_name': [f'Student_{i}' for i in range(1, 16)],
    'subject_1_marks': np.random.randint(40, 100, 15),
    'subject_2_marks': np.random.randint(40, 100, 15),
    'subject_3_marks': np.random.randint(40, 100, 15),
    'subject_4_marks': np.random.randint(40, 100, 15),
    'subject_5_marks': np.random.randint(40, 100, 15),
    'subject_6_marks': np.random.randint(40, 100, 15)
}

df_students = pd.DataFrame(student_data)


display(df_students.head())

,student_id,student_name,subject_1_marks,subject_2_marks,subject_3_marks,subject_4_marks,subject_5_marks,subject_6_marks
0,1,Student_1,78,95,63,73,59,49
1,2,Student_2,79,98,78,55,73,90
2,3,Student_3,88,75,77,84,77,85
3,4,Student_4,45,78,96,82,66,89
4,5,Student_5,69,78,84,67,47,86

In [5]:
value_vars = ['subject_1_marks', 'subject_2_marks', 'subject_3_marks', 'subject_4_marks', 'subject_5_marks', 'subject_6_marks']
df_long = df_students.melt(id_vars=['student_id', 'student_name'], value_vars=value_vars, var_name='subject', value_name='marks')
display(df_long.head())

   student_id student_name          subject  marks
0           1    Student_1  subject_1_marks     78
1           2    Student_2  subject_1_marks     79
2           3    Student_3  subject_1_marks     88
3           4    Student_4  subject_1_marks     45
4           5    Student_5  subject_1_marks     69

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [6]:

np.random.seed(42)
placement_data = {
    'student_id': range(1, 16),
    'CGPA': np.round(np.random.uniform(6.0, 9.8, 15), 2),
    'companies_appeared': np.random.randint(1, 11, 15),
    'company_placed': np.random.choice(['Company A', 'Company B', 'Company C', 'Company D', 'None'], 15, p=[0.2, 0.2, 0.2, 0.2, 0.2])
}
df_placement = pd.DataFrame(placement_data)

display(df_placement.head())

   student_id  CGPA  companies_appeared company_placed
0           1  7.42                   5      Company A
1           2  9.61                   1      Company A
2           3  8.78                  10           None
3           4  8.27                   6           None
4           5  6.59                   9           None

In [7]:

df_merged = pd.merge(df_students, df_placement, on='student_id')

print("Merged DataFrame head:")
display(df_merged.head())

Merged DataFrame head:

,student_id,student_name,subject_1_marks,subject_2_marks,subject_3_marks,subject_4_marks,subject_5_marks,subject_6_marks,CGPA,companies_appeared,company_placed
0,1,Student_1,78,95,63,73,59,49,7.42,5,Company A
1,2,Student_2,79,98,78,55,73,90,9.61,1,Company A
2,3,Student_3,88,75,77,84,77,85,8.78,10,None
3,4,Student_4,45,78,96,82,66,89,8.27,6,None
4,5,Student_5,69,78,84,67,47,86,6.59,9,None

### Students with CGPA above 7.5

In [8]:

students_high_cgpa = df_merged[df_merged['CGPA'] > 7.5]

print(f"Number of students with CGPA above 7.5: {len(students_high_cgpa)}")
print("Details of students with CGPA above 7.5:")
display(students_high_cgpa)

Number of students with CGPA above 7.5: 8
Details of students with CGPA above 7.5:

,student_id,student_name,subject_1_marks,subject_2_marks,subject_3_marks,subject_4_marks,subject_5_marks,subject_6_marks,CGPA,companies_appeared,company_placed
1,2,Student_2,79,98,78,55,73,90,9.61,1,Company A
2,3,Student_3,88,75,77,84,77,85,8.78,10,None
3,4,Student_4,45,78,96,82,66,89,8.27,6,None
7,8,Student_8,93,66,87,40,67,63,9.29,3,Company D
8,9,Student_9,57,69,65,46,99,70,8.28,7,Company C
9,10,Student_10,88,80,95,92,73,99,8.69,4,Company A
11,12,Student_12,66,88,48,90,95,51,9.69,3,Company A
12,13,Student_13,81,58,46,44,81,64,9.16,5,None

### Students placed in a particular company

In [9]:

target_company = 'Company A'


students_placed_in_company = df_merged[df_merged['company_placed'] == target_company]

print(f"Number of students placed in '{target_company}': {len(students_placed_in_company)}")


print(f"Details of students placed in '{target_company}':")
display(students_placed_in_company)

Number of students placed in 'Company A': 5
Details of students placed in 'Company A':

,student_id,student_name,subject_1_marks,subject_2_marks,subject_3_marks,subject_4_marks,subject_5_marks,subject_6_marks,CGPA,companies_appeared,company_placed
0,1,Student_1,78,95,63,73,59,49,7.42,5,Company A
1,2,Student_2,79,98,78,55,73,90,9.61,1,Company A
6,7,Student_7,60,76,97,69,42,83,6.22,10,Company A
9,10,Student_10,88,80,95,92,73,99,8.69,4,Company A
11,12,Student_12,66,88,48,90,95,51,9.69,3,Company A